using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MsgRpc.Generator;

/// <summary>
/// Incremental Source Generator for MsgRpc. 
/// Automatically generates Proxies (Client-side) and Dispatchers (Server-side) for interfaces 
/// marked with [MsgRpcService].
/// </summary>
[Generator]
public class MsgRpcGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Filter syntax: Find interfaces with at least one attribute.
        // Incremental providers are highly efficient as they only re-run on relevant changes.
        var serviceDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is InterfaceDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (ctx, _) => GetServiceMetadata(ctx))
            .Where(m => m is not null);

        // 2. Register the source output: Actually write the generated .g.cs files.
        context.RegisterSourceOutput(serviceDeclarations, (spc, metadata) =>
        {
            if (metadata == null) return;
            // Generate unique filename and UTF-8 source code
            spc.AddSource($"{metadata.InterfaceName}.g.cs", SourceText.From(GenerateSource(metadata), Encoding.UTF8));
        });
    }

    /// <summary>
    /// Extracts metadata from the semantic model of the interface.
    /// This includes service names, method IDs, parameters, and return types.
    /// </summary>
    private ServiceMetadata? GetServiceMetadata(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not InterfaceDeclarationSyntax interfaceDecl) return null;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(interfaceDecl) as INamedTypeSymbol;
        if (symbol == null) return null;

        // Check if the interface is marked with [MsgRpcService]
        var serviceAttr = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "MsgRpcServiceAttribute");
        if (serviceAttr == null) return null;

        var metadata = new ServiceMetadata
        {
            Namespace = symbol.ContainingNamespace.ToDisplayString(),
            InterfaceName = symbol.Name,
            ServiceName = serviceAttr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? symbol.Name,
            Methods = new List<MethodMetadata>()
        };

        // Analyze methods marked with [MsgRpc]
        foreach (var member in symbol.GetMembers().OfType<IMethodSymbol>())
        {
            var methodAttr = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "MsgRpcAttribute");
            if (methodAttr == null) continue;

            // Handle Task vs Task<T>
            bool isVoid = member.ReturnType.ToDisplayString() == "System.Threading.Tasks.Task";
            string returnType = isVoid ? "MessagePack.Nil" :
                ((member.ReturnType as INamedTypeSymbol)?.TypeArguments.FirstOrDefault()?.ToDisplayString() ?? "object");

            metadata.Methods.Add(new MethodMetadata
            {
                MethodId = (uint)(methodAttr.ConstructorArguments.FirstOrDefault().Value ?? 0),
                MethodName = member.Name,
                FullReturnType = member.ReturnType.ToDisplayString(),
                UnwrappedReturnType = returnType,
                IsVoid = isVoid,
                Parameters = member.Parameters.Select(p => new ParameterMetadata { Name = p.Name, Type = p.Type.ToDisplayString() }).ToList()
            });
        }
        return metadata;
    }

    /// <summary>
    /// Generates the C# source code for:
    /// 1. MessagePack DTOs for arguments and results.
    /// 2. Client Proxy (translates method calls to network requests).
    /// 3. Server Dispatcher (translates network requests to local service calls).
    /// 4. Fluent Extension methods for registration.
    /// </summary>
    private string GenerateSource(ServiceMetadata m)
    {
        var proxyName = $"{m.InterfaceName}Proxy";
        var dispatcherName = $"{m.InterfaceName}Dispatcher";
        var serviceShortName = m.InterfaceName.StartsWith("I") ? m.InterfaceName.Substring(1) : m.InterfaceName;

        var sb = new StringBuilder();
        sb.AppendLine($$"""
// <auto-generated/>
using System;
using System.Buffers;
using System.Threading.Tasks;
using MessagePack;
using Microsoft.Extensions.DependencyInjection;
using MsgRpc.Abstractions;

namespace {{m.Namespace}}
{
    // --- DTOs (ReadOnly Structs for Performance) ---
""");

        foreach (var method in m.Methods)
        {
            var prefix = $"{m.InterfaceName}_{method.MethodName}";
            var paramDecls = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
            
            // Generate a dedicated argument DTO for each method
            sb.AppendLine($$"""
    [MessagePackObject]
    public readonly struct {{prefix}}Args 
    {
""");
            for (int i = 0; i < method.Parameters.Count; i++)
                sb.AppendLine($"        [Key({i})] public {method.Parameters[i].Type} {method.Parameters[i].Name} {{ get; init; }}");

            sb.AppendLine($$"""
        public {{prefix}}Args({{paramDecls}})
        {
            {{string.Join(" ", method.Parameters.Select(p => $"this.{p.Name} = {p.Name};"))}}
        }
    }

    // Generate a dedicated result wrapper
    [MessagePackObject]
    public readonly struct {{prefix}}Result 
    {
        [Key(0)] public {{method.UnwrappedReturnType}} Value { get; init; }
        public {{prefix}}Result({{method.UnwrappedReturnType}} value) => Value = value;
    }
""");
        }

        // --- Proxy Implementation (Client Side) ---
        sb.AppendLine($$"""
    internal sealed class {{proxyName}} : {{m.InterfaceName}}
    {
        private readonly IMsgRpcClient _client;
        public {{proxyName}}(IMsgRpcClient client) => _client = client;

""");

        foreach (var method in m.Methods)
        {
            var prefix = $"{m.InterfaceName}_{method.MethodName}";
            var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var argPassing = string.Join(", ", method.Parameters.Select(p => p.Name));

            // Proxy serializes args, calls transport, and deserializes response
            sb.AppendLine($$"""
        public async {{method.FullReturnType}} {{method.MethodName}}({{paramList}})
        {
            var args = new {{prefix}}Args({{argPassing}});
            var writer = new ArrayBufferWriter<byte>(256);
            MessagePackSerializer.Serialize(writer, args);
            
            var response = await _client.CallAsync("{{m.ServiceName}}", {{method.MethodId}}, new ReadOnlySequence<byte>(writer.WrittenMemory), default);
            var result = MessagePackSerializer.Deserialize<{{prefix}}Result>(response);
            {{(method.IsVoid ? "return;" : "return result.Value;")}}
        }
""");
        }
        sb.AppendLine("    }");

        // --- Dispatcher Implementation (Server Side) ---
        sb.AppendLine($$"""
    internal sealed class {{dispatcherName}} : IServiceDispatcher
    {
        private readonly {{m.InterfaceName}} _service;
        public {{dispatcherName}}({{m.InterfaceName}} service) => _service = service;

        public async Task<ReadOnlyMemory<byte>> DispatchAsync(uint methodId, ReadOnlySequence<byte> payload)
        {
            switch (methodId)
            {
""");

        foreach (var method in m.Methods)
        {
            var prefix = $"{m.InterfaceName}_{method.MethodName}";
            var callArgs = string.Join(", ", method.Parameters.Select(p => $"args.{p.Name}"));
            
            // Dispatcher maps MethodId to the actual implementation call
            sb.AppendLine($$"""
                case {{method.MethodId}}:
                    {
                        var args = MessagePackSerializer.Deserialize<{{prefix}}Args>(payload);
                        {{(method.IsVoid ? "" : "var res = ")}}await _service.{{method.MethodName}}({{callArgs}});
                        var resultWrapper = new {{prefix}}Result({{(method.IsVoid ? "Nil.Default" : "res")}});
                        return MessagePackSerializer.Serialize(resultWrapper);
                    }
""");
        }

        sb.AppendLine($$"""
                default:
                    throw new InvalidOperationException($"Method {methodId} not found");
            }
        }
    }
}

namespace MsgRpc
{
    using global::{{m.Namespace}};

    /// <summary>
    /// Generated helper methods for {{m.InterfaceName}}.
    /// </summary>
    public static class {{m.InterfaceName}}Extensions
    {
        /// <summary>
        /// Server-side registration: Registers the service and binds its generated Dispatcher.
        /// </summary>
        public static MsgRpcServerBuilder With{{serviceShortName}}<TImplementation>(this MsgRpcServerBuilder builder)
            where TImplementation : class, {{m.InterfaceName}}
        {
            builder.AddService<{{m.InterfaceName}}, TImplementation>();
            builder.RegisterDispatcherInternal((server, provider) => 
            {
                var service = provider.GetRequiredService<{{m.InterfaceName}}>();
                ((MsgRpcServer)server).RegisterServiceInternal("{{m.ServiceName}}", new {{dispatcherName}}(service));
            });
            return builder;
        }

        /// <summary>
        /// Client-side creation: Wraps a raw IMsgRpcClient in a typed Proxy.
        /// </summary>
        public static {{m.InterfaceName}} Create{{serviceShortName}}(this MsgRpc.Abstractions.IMsgRpcClient client) 
            => new {{proxyName}}(client);
    }
}
""");

        return sb.ToString();
    }

    #region Helper Metadata Classes
    
    private class ServiceMetadata
    {
        public string Namespace { get; set; } = null!;
        public string InterfaceName { get; set; } = null!;
        public string ServiceName { get; set; } = null!;
        public List<MethodMetadata> Methods { get; set; } = null!;
    }
    private class MethodMetadata
    {
        public uint MethodId;
        public string MethodName = null!, FullReturnType = null!, UnwrappedReturnType = null!;
        public bool IsVoid;
        public List<ParameterMetadata> Parameters = null!;
    }
    private class ParameterMetadata
    {
        public string Name = null!, Type = null!;
    }
    #endregion
}