using System.Buffers;

namespace MsgRpc.Abstractions;

/// <summary>
/// Defines the core contract for an RPC service dispatcher.
/// </summary>
/// <remarks>
/// For every RPC service interface, a corresponding dispatcher implementation is 
/// automatically generated by the Source Generator. Its primary responsibilities include 
/// rehydrating binary parameters into concrete types and invoking the actual service logic.
/// </remarks>
public interface IServiceDispatcher
{
    /// <summary>
    /// Dispatches an incoming request to the appropriate service method based on the method identifier.
    /// </summary>
    /// <param name="methodId">The unique identifier of the method to be invoked within this service.</param>
    /// <param name="payload">The raw, serialized request parameters as a <see cref="ReadOnlySequence{Byte}"/>.</param>
    /// <returns>
    /// A <see cref="Task{T}"/> containing the serialized result of the method execution 
    /// as a <see cref="ReadOnlyMemory{Byte}"/>.
    /// </returns>
    /// <remarks>
    /// This method acts as the "glue" between the transport layer and the high-level C# service implementation, 
    /// enabling high-performance, reflection-free method invocation.
    /// </remarks>
    Task<ReadOnlyMemory<byte>> DispatchAsync(uint methodId, ReadOnlySequence<byte> payload);
}