using System.Buffers;
using System.Collections.Concurrent;
using System.Net;
using MessagePack;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using MsgRpc.Abstractions;

namespace MsgRpc;

/// <summary>
/// The core implementation of the MsgRpc server.
/// Optimized for high-concurrency scenarios using <see cref="ArrayPool{T}"/> memory reuse, 
/// high-performance <see cref="LoggerMessage"/>, and deep integration with the MessagePack framework.
/// </summary>
public sealed partial class MsgRpcServer : IMsgRpcServer
{
    private readonly IServerTransport _transport;
    private readonly ILogger<MsgRpcServer> _logger;
    private readonly MessagePackSerializerOptions _options;
    private readonly ConcurrentDictionary<string, IServiceDispatcher> _dispatchers = new();
    private readonly CancellationTokenSource _serverCts = new();
    private bool _isDisposed;

    /// <summary>
    /// Initializes a new instance of the <see cref="MsgRpcServer"/> class.
    /// </summary>
    /// <param name="transport">The transport layer implementation (e.g., <see cref="Transports.Tcp.TcpServerTransport"/>).</param>
    /// <param name="options">The MessagePack serialization settings to ensure compatibility with clients.</param>
    /// <param name="logger">Optional logger for server diagnostics.</param>
    public MsgRpcServer(
        IServerTransport transport, 
        MessagePackSerializerOptions options,
        ILogger<MsgRpcServer>? logger = null)
    {
        _transport = transport ?? throw new ArgumentNullException(nameof(transport));
        _options = options ?? MessagePackSerializerOptions.Standard;
        _logger = logger ?? NullLogger<MsgRpcServer>.Instance;
    }

    #region High-Performance Logging (Source Generated)

    [LoggerMessage(EventId = 1, Level = LogLevel.Information, Message = "[Server] Starting listener on: {EndPoint}")]
    private static partial void LogStarting(ILogger logger, EndPoint endPoint);

    [LoggerMessage(EventId = 2, Level = LogLevel.Error, Message = "[Server] Request processing failed [ID:{RequestId}]: {Message}")]
    private static partial void LogRequestError(ILogger logger, uint requestId, string message);

    [LoggerMessage(EventId = 3, Level = LogLevel.Warning, Message = "[Server] Attempted to call non-existent service: {ServiceName}")]
    private static partial void LogServiceNotFound(ILogger logger, string serviceName);

    [LoggerMessage(EventId = 4, Level = LogLevel.Information, Message = "[Server] Server has shut down.")]
    private static partial void LogServerStopped(ILogger logger);

    #endregion

    /// <summary>
    /// Registers a service dispatcher implementation, typically created by the Source Generator.
    /// This is intended for internal framework use.
    /// </summary>
    public void RegisterServiceInternal(string serviceName, IServiceDispatcher dispatcher)
    {
        if (string.IsNullOrEmpty(serviceName)) throw new ArgumentException("Service name cannot be null or empty.", nameof(serviceName));
        _dispatchers[serviceName] = dispatcher ?? throw new ArgumentNullException(nameof(dispatcher));
    }

    /// <summary>
    /// Traditional registration interface. 
    /// Note: Direct instance registration is currently not supported; use Source Generator extension methods instead.
    /// </summary>
    public void RegisterService<TService>(string serviceName, TService implementation) where TService : class
        => throw new NotSupportedException("Please use the 'With{ServiceName}' extension methods generated by the Source Generator for registration.");

    /// <summary>
    /// Starts the server listening for incoming RPC requests on the specified endpoint.
    /// </summary>
    public async Task StartAsync(EndPoint endPoint)
    {
        LogStarting(_logger, endPoint);
        await _transport.StartAsync(endPoint, HandleRequestAsync, _serverCts.Token);
    }

    /// <summary>
    /// The core request processing entry point. 
    /// Implements a non-blocking design: immediately clones the payload and dispatches processing 
    /// to the thread pool to avoid stalling IO threads.
    /// </summary>
    /// <param name="connectionId">The unique ID of the client connection.</param>
    /// <param name="requestId">The sequence ID assigned by the client.</param>
    /// <param name="payload">The raw request byte sequence.</param>
    /// <returns>A <see cref="Task"/> representing the synchronous part of the dispatch (always completed).</returns>
    public Task HandleRequestAsync(Guid connectionId, uint requestId, ReadOnlySequence<byte> payload)
    {
        // 1. Immediately rent memory from the ArrayPool and copy the payload.
        // This MUST be done synchronously because the Transport layer may release 
        // the ReadOnlySequence once this method returns.
        int payloadLen = (int)payload.Length;
        byte[] rentedArray = ArrayPool<byte>.Shared.Rent(payloadLen);
        payload.CopyTo(rentedArray);

        // 2. Dispatch the actual business logic to the Task Parallel Library (TPL) thread pool.
        _ = Task.Run(async () =>
        {
            var writer = new ArrayBufferWriter<byte>(1024);
            var ct = _serverCts.Token;

            try
            {
                if (ct.IsCancellationRequested) return;

                MsgRpcResponse response;
                try
                {
                    // 3. Deserialize the request using the injected MessagePack options.
                    var request = MessagePackSerializer.Deserialize<MsgRpcRequest>(
                        new ReadOnlySequence<byte>(rentedArray, 0, payloadLen), 
                        _options);

                    if (_dispatchers.TryGetValue(request.ServiceName, out var dispatcher))
                    {
                        // 4. Execute the business logic via the dispatcher.
                        var result = await dispatcher.DispatchAsync(request.MethodId, new ReadOnlySequence<byte>(request.Parameters));
                        
                        // 5. Construct a successful response.
                        response = new MsgRpcResponse(true, result.ToArray());
                    }
                    else
                    {
                        LogServiceNotFound(_logger, request.ServiceName ?? "Unknown");
                        response = new MsgRpcResponse(false, Array.Empty<byte>(), "Service not found");
                    }
                }
                catch (Exception ex)
                {
                    LogRequestError(_logger, requestId, ex.Message);
                    response = new MsgRpcResponse(false, Array.Empty<byte>(), ex.Message);
                }

                // 6. Serialize the response and transmit it via the transport layer.
                MessagePackSerializer.Serialize(writer, response, _options);
                await _transport.SendResponseAsync(connectionId, requestId, writer.WrittenMemory, ct);
            }
            catch (OperationCanceledException) { /* Expected shutdown behavior */ }
            catch (Exception ex)
            {
                // Network errors are logged at Trace level to prevent log pollution under high load.
                _logger.LogTrace(ex, "Network error while sending response [Conn:{ConnectionId}, ID:{RequestId}]", connectionId, requestId);
            }
            finally
            {
                // 7. CRITICAL: Return the rented memory to the pool to prevent memory leaks.
                ArrayPool<byte>.Shared.Return(rentedArray);
            }
        }, _serverCts.Token);

        return Task.CompletedTask;
    }

    /// <summary>
    /// Asynchronously shuts down the server, stops listening, and releases all resources.
    /// </summary>
    public async ValueTask DisposeAsync()
    {
        if (_isDisposed) return;
        _isDisposed = true;

        _serverCts.Cancel();
        
        // Stop the transport layer before disposing of the CancellationSource.
        await _transport.DisposeAsync();
        _serverCts.Dispose();
        
        LogServerStopped(_logger);
    }
}